### ISSUE TITLE
Add `teal.reporter` into tmh modules

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.modules.hermes#238]
- blocked by https://github.com/insightsengineering/teal.modules.clinical/issues/505
After https://github.com/insightsengineering/teal/pull/635 teal applications can be used to generate reports - do we want them added into tmh as well?

**Comment by mhallal1** [comment]
@danielinteractive Could you list the specific encodings that are needed for every module to be included in the report?
For instance: https://github.com/insightsengineering/teal.osprey/issues/140#issuecomment-1177840597

**Comment by danielinteractive** [comment]
@mhallal1 maybe it is easiest just to include all?
