### ISSUE TITLE
Move scda to suggests

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.modules.hermes#264]
### Feature description

Other packages use scda only in SUGGESTs (i.e. for examples ) shouldn't tmh as well?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
@nikolas-burkoff yeah good idea

**Comment by donyunardi** [comment]
This has been completed.
