### ISSUE TITLE
Fix errors on main 

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal.modules.hermes#266]
Idea: When running the tests with testing depth 5, errors exist on main branch:
![Screenshot from 2022-07-12 17-59-31](https://user-images.githubusercontent.com/86970066/178538864-43dbd0df-8975-4050-817f-91e10a879929.png)

To do:

- [ ] check out latest main branch, make feature branch for this issue
- [ ] run staged.dependencies install upstream dependencies and this package
- [ ] Replicate test failures with testing depth 5
	- [ ] run `Sys.setenv(TESTING_DEPTH = 5)` in R
	- [ ] afterwards test or check the package
- [ ] fix the failures
	- [ ] could be just accepting minor plot differences
	- [ ] or could be something else - then edit this task description accordingly

Note: Seems like only somebody with Linux or Mac OS or Docker image can work on this task. Windows has security blocking the phantomJS browser for shiny tests.

**Comment by danielinteractive** [comment]
@dinakar29 can we double check again that tmh tests are run with testing depth 5 during integration tests? I remember we discussed this in the past and you wanted to activate those. I have the feeling we might still not run them and catch those test problems early?

**Comment by sob2021** [comment]
Hello,
Test report:
![image](https://user-images.githubusercontent.com/95754054/180170209-b7b40891-a199-42b6-b639-3666a58c092e.png)

The following error seems to be common across all 17 failures, please what does this mean?
![image](https://user-images.githubusercontent.com/95754054/180170640-8f560203-1e9a-466b-8915-76dd53a06235.png)

**Comment by danielinteractive** [comment]
@sob2021 oops, seems like you are not allowed by the operating system to run the Shiny tests. I guess somebody else needs to do this task then

**Comment by sob2021** [comment]
oh ok, thanks @danielinteractive, no worries.

**Comment by nikolas-burkoff** [comment]
Worth being aware of 
- https://github.com/rstudio/shinytest/issues/412 (and its link https://github.com/rstudio/shinytest2/issues/4)  
- https://github.com/rstudio/shinytest/issues/382 and especially this 
- https://github.com/rstudio/shinytest/issues/270

**Comment by danielinteractive** [comment]
this was closed in #286
