### ISSUE TITLE
[UAT] Test teal.reporter in modules

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.modules.hermes#284]

**Comment by danielinteractive** [comment]
Observations from my UAT:
- [ ] https://github.com/insightsengineering/teal.modules.hermes/blob/ebcbe5a47362da8229c49a8677c21c37a3468c62/R/volcanoplot.R#L203: "Scatter Plot" should be replaced by "Volcano Plot"

**Comment by danielinteractive** [comment]
General comment on the reporter titles: would it be possible to have the title not hardcoded within each module but taking whatever the module is called in the app? I think that would help a lot 1) to keep the code maintainable and 2) to make it easier for the user to understand which reporter output belongs to which tab.
(@gogonzo @nikolas-burkoff fyi)

**Comment by nikolas-burkoff** [comment]
@danielinteractive we have this issue https://github.com/insightsengineering/teal.reporter/issues/94 - I'll add your comment there
