### ISSUE TITLE
KM module red error

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/teal.modules.hermes#287]
### What happened?

![image](https://user-images.githubusercontent.com/1071227/195604348-d2d80b09-be2b-4d75-b57a-883cfca9b197.png)

### sessionInfo()

```R
on current main branch
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I can still reproduce this error

**Comment by danielinteractive** [comment]
@Melkiades can you please be more specific - e.g. did you install from main branch with staged dependencies and it happened?

**Comment by Melkiades** [comment]
I used the app deployed today (from which the screenshot comes from).
 
![Screenshot 2022-10-13 173906](https://user-images.githubusercontent.com/11279768/195642429-93198bf4-7633-429c-a268-4fdcdbe5617b.png)

I think it is just the fact that there is only one `TRUE` after filtering. Probably not a common case eheh

**Comment by danielinteractive** [comment]
yeah sure the deployed thing still has that problem. the fix was on main branch. I close these issues when I fix on main

**Comment by Melkiades** [comment]
I see! Sorry for the misunderstanding!!
