### ISSUE TITLE
example is dead

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.hermes#299]
### What happened?

Example in README uses deprecated `teal` function `root_modules` and thus cannot be run.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
Thanks, nice catch , if you can help us fix it would be great

**Comment by chlebowa** [comment]
It seems it is going to be fixed by #300, the example is moved from README to a vignette and `root_modules` is replaced with `teal::modules`.
