### ISSUE TITLE
Review `tmhermes` documentation before release

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.modules.hermes#307]
### Summary
Related with insightsengineering/nestdevs-tasks#25
and also: https://github.com/insightsengineering/teal.modules.hermes/pull/294
In preparation to release, we need to review/assess all documentation in the package. 

### Acceptance Criteria
* Review roxygen examples on all functions
  * Test examples
  * ~~If it's using chunk, update to `qenv`.~~
* Review vignettes on these topics only:
  * ~~Review any content around `qenv`~~
  * ~~Review any content around `chunks` (i.e. make sure the right language around deprecation)~~
  * Review any content around shinyvalidate
* redo the content of WORDLIST
  * ~~For instruction on how to do this, visit https://github.com/insightsengineering/coredev-tasks/issues/235~~
  * Provieded here https://github.com/insightsengineering/teal.modules.hermes/pull/310
* Update NEWS
* Update README (if applicable)
* Review DESCRIPTION file (i.e check dependency versions, etc)
  * Be sure to update teal.code dependency to be >= 0.3.0

**Comment by donyunardi** [comment]
Closing this issue as `chunks` is not used in this module.

Confirmed that the `chunks` mentioned [here](https://github.com/search?q=org%3Ainsightsengineering+repo%3Ainsightsengineering%2Fteal.modules.hermes++chunks&type=code) is just a design files and not part of R package (see comment [here](https://github.com/insightsengineering/nestdevs-tasks/issues/23#issuecomment-1564728562)).

@danielinteractive please update the mentioned design files to use `qenv` if needed and remove any reference to `chunks` to avoid future confusion.

**Comment by donyunardi** [comment]
Sorry, reopen this again.
Even though `chunks` is out of the picture, we still need to release this due to update during the refactor:
https://github.com/insightsengineering/teal.modules.hermes/pull/294

**Comment by m7pr** [comment]
Hey @gogonzo I did review this package. There is no use of teal.code::chunks in examples, regular code nor vignettes. The only place this is used is a `design/` folder (those two files https://github.com/search?q=org%3Ainsightsengineering+repo%3Ainsightsengineering%2Fteal.modules.hermes++chunks&type=code) but this folder is listed in `.Rbuildignore` so it's not a part of the package. 

Also no need to add teal.code to dependencies in `DESCRIPTION`

**Comment by danielinteractive** [comment]
@gogonzo the point is that `design` folder contains many outdated things, it is a memory of the project. Therefore you can consider this as it does not have to work at all, but it can be helpful later for us when understanding the history. so we can just keep it like it is.

**Comment by m7pr** [comment]
so I guess we can close this issue
