### ISSUE TITLE
[Bug]: Uncaught error in Scatterplot module

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.hermes#320]
In [RNA-seq app](https://genentech.shinyapps.io/nest_rna-seq_main/):
+ Scatterplot
+ Select Experiment - hd2
+ Selected Assay - any
+ Selected x/y genes - any
+ Select Gene Summary - any
+ Optional color variable - any selection
+ Optional facet variable - any selection
+ Filter Panel - select any numeric variable from subjects with a range slider and apply filter

`Error: 9 elements in value to replace 5 elements`
(numbers may vary)

If this error is expected, use a validation mechanism to capture it.

**Comment by danielinteractive** [comment]
probably solved by #326 , @BFalquet to confirm

**Comment by BFalquet** [comment]
Issue appears to have been solved by #326
