### ISSUE TITLE
[Bug]: Uncaught error in Kaplan-Meier module, sometimes crashes

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.hermes#321]
In [RNA-seq app](https://genentech.shinyapps.io/nest_rna-seq_main/):

Kaplan-Meier
+ Select Experiment - hd2
+ Select Assay - any
+ Select Genes - any
+ Select Gene Summary - any
+ Select Endpoint - OS/PFS
+ Select Strata - COHORT (perhaps others)
+ Filter Panel: subjects > DURSAF > apply filter

also with DURDIF

`Error: Lapack routine dgesv: system is exactly singular: U[1,1] = 0`

OR application crashes (disconnected from server)

**Comment by danielinteractive** [comment]
Hm thanks we should indeed try to catch this error and return validation message

**Comment by gogonzo** [comment]
Sees to be addressed by this 
https://github.com/insightsengineering/teal.modules.hermes/pull/326
