### ISSUE TITLE
 [Bug]: Uncaught error in Barplot module

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal.modules.hermes#323]
### What happened?

In [RNA-seq app](https://genentech.shinyapps.io/nest_rna-seq_main/):

- Barplot
- Select Experiment - hd2
- Selected Assay - any
- Optional facet variable - any
- Selected Genes - any
- Select Gene Summary - any
- Select Quantiles - any
- Filter Panel - select any filter that reduces size of the data

`Error: 5 elements in value to replace 4 elements`
(numbers may vary)

It stems from `multiSampleVarSpecServer(...)$experiment_data()` call _(see line below)_:

https://github.com/insightsengineering/teal.modules.hermes/blob/11ee3086b0be214d264e98d80d79eb91c1f80383/R/barplot.R#L151

If this error is expected, use a validation mechanism to capture it.

This error is probably related to #320 

#### Screenshot

![image](https://github.com/insightsengineering/teal.modules.hermes/assets/211358/dd3851b3-c947-46d6-823d-20ec54415105)

**Comment by danielinteractive** [comment]
Thanks, @BFalquet would you have time to look at it?
