### ISSUE TITLE
`R CMD check` consumes a large amount of memory

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.modules.hermes#361]
### What happened?

Running R CMD check on this package consumes a large amount of memory, almost to a point where total amount of available memory gets saturated.

See memory consumption graph when `R CMD check --ignore-vignettes teal.modules.hermes_0.1.6.9001.tar.gz ` is run on a R 4.3.1 + BioC 3.18 container:

![image](https://github.com/insightsengineering/teal.modules.hermes/assets/26552821/0a6cd8c9-ddbe-47bf-bdca-430837b1006f)

### sessionInfo()

I can supply the `renv.lock` for reference. Cannot post it here due to the character limit for issue bodies imposed by GitHub (maximum is 65536 characters).

### Relevant log output

The actual check runs fine when run in isolation.

The real issue happens when there are other R CMD checks or other processes that run alongside this one. The resulting issue is a memory leak and the following error in the log:

```R

  In callback(...) :
    Chromote has received a Inspector.targetCrashed event. This means that the ChromoteSession has probably crashed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
Thanks @cicdguy , how about other `teal.modules.*` packages? Do we see a similarly increasing, almost linear over time consumption of memory?

For now let's try to put https://rstudio.github.io/shinytest2/reference/AppDriver.html#method-AppDriver-stop into each shiny test.

**Comment by BFalquet** [comment]
The 2 first test files and the 11th (which could correspond to the plateau in mid-curve) are the only test file where we are not performing snapshot tests. Maybe there is a glitch there.

**Comment by danielinteractive** [comment]
Hm interesting ... let's see after we add the stop commands what happens

**Comment by danielinteractive** [comment]
If this does not help, we could try 

- reproduce locally
- interrogate locally where the memory is consumed
- find out root cause like that

**Comment by danielinteractive** [comment]
@cicdguy is it better now?

**Comment by walkowif** [comment]
This is the current memory consumption of tests running only for `teal.modules.hermes`:
![process-memory](https://github.com/insightsengineering/teal.modules.hermes/assets/59475134/8e59ca2c-6ea4-442b-9562-044d0a569dbe)

Here's the [test log](https://github.com/insightsengineering/teal.modules.hermes/files/14419324/tmh.log).

**Comment by danielinteractive** [comment]
good to know and learn about it! thanks @cicdguy and @walkowif !
