### ISSUE TITLE
use `teal.devel::plot_with_settings` for static plots

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.modules.hermes#61]
For all static graph type of the outputs please consider using `teal.widgets::plot_with_settings` functionality (you won't find this function - there are two with `_srv` and `_ui` suffixes). It gives nice features such as download, resize and modal preview. 
![image](https://user-images.githubusercontent.com/12943682/131500995-13740cbe-403b-4707-bf93-d76c975dfaec.png)

The only requirement is to pass on a plot in form of reactive expression. For details / example please see the docs, as well as https://github.com/insightsengineering/teal.modules.hermes/blob/main/R/forestplot.R where it is already used.

To do:
- [x] Barplot
- [x] Boxplot
- [x] Kaplan-Meier Plot
- [ ] PCA plots
- [x] Quality module plots
- [x] Scatterplot
- [ ] Volcanoplot

**Comment by Polkas** [comment]
Please consider it once more as only one module is using `plot_with_settings` now. In my opinion we should be consistent so use it everywhere or nowhere.
